stages:
  - build_and_push

variables:
  # Docker 설정
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''

  # Docker 이미지 설정
  DOCKER_IMAGE_NAME: kube-test
  DOCKER_REGISTRY: 461338739533.dkr.ecr.ap-southeast-2.amazonaws.com

build_and_push:
  stage: build_and_push
  image: docker:latest
  services:
    - docker:19-dind
  before_script:
    - echo "Logging in to the container registry..."
    - apk add --no-cache curl jq python3 py3-pip
    - python3 -m venv venv
    - chmod +x ./venv/bin/activate
    - . ./venv/bin/activate
    - pip install awscli --no-build-isolation
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
    - docker info
    - docker --version
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE_NAME .
    - echo "Tagging Docker image..."
    - docker tag $DOCKER_IMAGE_NAME $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_PIPELINE_IID
    - echo "Pushing Docker image to ECR..."
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_PIPELINE_IID
  only:
    - develop
