stages:
  - build
  - push

variables:
  # AWS ECR 설정
  AWS_REGION: 'ap-southeast-2'
  ECR_REPO: 'kube-test'
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

  # Docker 설정
  DOCKER_HOST: 'tcp://docker:2375'
  DOCKER_DRIVER: 'overlay2'
  DOCKER_TLS_CERTDIR: ''

  # Docker 이미지 설정
  DOCKER_IMAGE_NAME: 'kube-test'
  CONTAINER_REGISTRY: '461338739533.dkr.ecr.ap-southeast-2.amazonaws.com'

build:
  stage: build
  image:
    name: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "Logging in to the container registry..."
    - echo "$AWS_SECRET_ACCESS_KEY" | docker login -u "$AWS_ACCESS_KEY_ID" --password-stdin $CONTAINER_REGISTRY
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE_NAME .
  only:
    - develop

push:
  stage: push
  image:
    name: docker:latest
  before_script:
    - echo "Logging in to the container registry..."
    - echo "$AWS_SECRET_ACCESS_KEY" | docker login -u "$AWS_ACCESS_KEY_ID" --password-stdin $CONTAINER_REGISTRY
  script:
    - echo "Tagging Docker image..."
    - docker tag $DOCKER_IMAGE_NAME $CONTAINER_REGISTRY/$ECR_REPO/$DOCKER_IMAGE_NAME:$CI_PIPELINE_IID
    - echo "Pushing Docker image to ECR..."
    - docker push $CONTAINER_REGISTRY/$ECR_REPO/$DOCKER_IMAGE_NAME:$CI_PIPELINE_IID
  only:
    - develop
